### ISSUE TITLE
Train and create a JSON Japanese user model

### ISSUE THREAD

**Issue by jsecretan** [brave-intl/bat-native-usermodel#6]
We are going to train a model for Japanese content, similar to what was done for the German model, from translated content into our current taxonomy.  In the short term, the model should match the short term interest with the ad, until we can train a more sophisticated one.

**Comment by ptigas** [comment]
Below is a break down of the tasks. I don't know how porter stemmer will interact with Japanese language though. Fingers crossed.

- [x]  translate corpus in japanese using google translate
- [ ]  fit a naive-bayes taxonomy model
- [ ]  integrate the model json files in usermodel

**Comment by tmancey** [comment]
"fit a naive-bayes taxonomy model" and "integrate the model json files in usermodel" are no longer required as implementation has changed to a hashing vector

**Comment by tmancey** [comment]
Completed however model needs improving
