### ISSUE TITLE
Some pages getting misclassified in user model

### ISSUE THREAD

**Issue by jsecretan** [brave-intl/bat-native-usermodel#7]
Based on feedback from our user group, some of this content is being misclassified:

1) https://www.curbed.com/ - Showing up as ["technology & computing","software"] probably more like "architecture" or "real estate"
2) https://www.apartmenttherapy.com/ - Saying not enough content to classify, but seems to be enough, and probably should be "architecture" or "real estate"

**Comment by tmancey** [comment]
This should be resolved by #16

**Comment by tmancey** [comment]
Closing issue as new machine learning models will work with the component updater
